### ISSUE TITLE
gulp test 运行报错！

### ISSUE THREAD

**Issue by git-lt** [progrape/weui.js#18]
```
[10:01:44] Starting 'test'...
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (/Users/liutao/work/demo/weui.js/node_modules/phantomjs-prebuilt/bin/phantomjs:22:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: test failed. phantomjs exit code: 1
```

**Comment by progrape** [comment]
@git-lt 一直出现？试试重新安装一下 `node_modules` 模块？
